.TH HELLO-NEWBIE "1"  "Sep 2015" "HELLO-NEWBIE 0.1" "say hello"
.SH NAME
\fBhello-newbie \fP- say hello
.SH DESCRIPTION
hello-newbie is a program that says hello to newbies.
.SH HOW TO USE
Just type 'hello-newbie' at command prompt.
.SH SEE ALSO
\fBhello\fP(1).
.SH AUTHOR
Hello Newbie was written by Joao Eriberto Mota Filho <eriberto@eriberto.pro.br>.
